apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-dns-setting
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,c2VhcmNoIDU0LnBhYXMudG9yb29uMTIuc3RyYXR1cy5pbnQuYmVsbC5jYQpuYW1lc2VydmVyIDEwLjI1NC4yNDkuMTk4Cm5hbWVzZXJ2ZXIgMTcyLjE4LjI0My4xNjY=
          filesystem: root
          mode: 0644
          path: /etc/resolv.conf