apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 4d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
    elasticsearch:
      nodeCount: 3
      nodeSelector:
          node-role.kubernetes.io/infra: ''
      storage:
        storageClassName: "local-blk"
        size: 200Gi
      redundancyPolicy: "MultipleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      nodeSelector:
          node-role.kubernetes.io/infra: ''
      replicas: 1
  collection:
    logs:
      type: "fluentd"
      fluentd: {}