apiVersion: apps/v1
kind: Deployment
metadata:
  name: parth-test-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpaca-trial
  template:
    metadata:
      labels:
        app: alpaca-trial
        ver: '1'
        env: prod
    spec:
      containers:
      - name: parth-test-1
        image: gcr.io/kuar-demo/kuard-amd64:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
