apiVersion: v1
kind: ServiceAccount
metadata:
  name: evnfm-admin-temp-sa
  namespace: proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: evnfm-sa-admin
  namespace: proxy
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: evnfm-sa-admin
  namespace: proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: evnfm-sa-admin
subjects:
- namespace: proxy
  kind: ServiceAccount
  name: evnfm-admin-temp-sa
