apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job-every-fifteen-mins
spec:
  schedule: "0,5,10,15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          containers:
            - name: main
              image: luksa/batch-job
          restartPolicy: OnFailure