apiVersion: v1
kind: Pod
metadata:
  name: kubia-unhealthy
  labels:
    name: kubia-unhealthy
spec:
  containers:
  - name: kubia-unhealthy
    image: luksa/kubia-unhealthy
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    livenessProbe:
      httpGet:
        port: 8080
        path: /
    ports:
      - containerPort: 8080
