apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-2
  labels:
    name: kubia
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - name: kubia 
    image: parthghetia/kubia  
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    ports:
      - containerPort: 8080
        protocol: TCP
