apiVersion: v1
kind: Pod
metadata:
  name: rsync
spec:
  nodeSelector:
    kubernetes.io/hostname: mxq10315tc
  containers:
  - image: busybox
    name: rsync
    volumeMounts:
    - mountPath: /src
      name: src
    args:
    - -c
    - sleep 8640000
    command:
    - sh
    resources:
      limits:
        cpu: "100m"
        memory: "1Gi"
  volumes:
  - name: src
    persistentVolumeClaim:
      claimName: test-dev
      readOnly: true