apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  volumes:
    - name: mongodb-data
      gcePersistentDisk:
        pdName: mongodb #should match the disk you created in google cloud
        fsType: ext4 #filesystem type is ext4 a linux type filesystem
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
      - mountPath: /data/db #path where mongodb stores its data
        name: mongodb-data
    ports:
      - containerPort: 27017
        protocol: TCP
