FROM node:7
# FROM defines teh container image that you'll be using. Node container image tag 7
ADD app.js /app.js
# adding app.js file from local dir to root dir of image
ENTRYPOINT ["node", "app.js"]
# specifying what command should be run when somebody runs the image

